namespace DataPortStudio.Services;

/// <summary>Translation tables. English is the fallback; Spanish is the first added language.</summary>
public static class Strings
{
    public static string Get(string key, string lang)
    {
        if (lang == "es" && Es.TryGetValue(key, out var es)) return es;
        return En.TryGetValue(key, out var en) ? en : key;
    }

    public static readonly Dictionary<string, string> En = new(StringComparer.Ordinal)
    {
        // Menu — File
        ["Menu_File"] = "_File",
        ["Menu_NewConnection"] = "New Connection",
        ["Menu_NewQuery"] = "New Query",
        ["Menu_QueryBuilder"] = "Query Builder",
        ["Menu_ExportTable"] = "Export current table…",
        ["Menu_Settings"] = "Settings…",
        ["Menu_Exit"] = "Exit",
        // Menu — Connection
        ["Menu_Connection"] = "_Connection",
        ["Menu_AddConnection"] = "Add Connection",
        ["Menu_EditConnection"] = "Edit Connection",
        ["Menu_RemoveConnection"] = "Remove Connection",
        ["Menu_Refresh"] = "Refresh",
        // Menu — View
        ["Menu_View"] = "_View",
        ["Menu_StructurePanel"] = "Structure panel",
        ["Menu_SqlPanel"] = "SQL preview panel",
        ["Menu_CellDetailPanel"] = "Cell detail panel",
        // Menu — Help
        ["Menu_Help"] = "_Help",
        ["Menu_Documentation"] = "User Guide",
        ["Help_Title"] = "DataPortStudio — User Guide",
        ["Menu_GitHub"] = "GitHub Repository",
        ["Menu_LatestRelease"] = "Latest Release",
        ["Menu_About"] = "About DataPortStudio",

        // Sidebar
        ["Sidebar_Connections"] = "CONNECTIONS",
        ["Filter_TablesPlaceholder"] = "Filter tables…",
        ["Filter_TablesTooltip"] = "Type to filter tables (and schemas/databases) by name",
        ["Btn_Add"] = "Add",
        ["Btn_Edit"] = "Edit",
        ["Btn_Remove"] = "Remove",
        ["Btn_Refresh"] = "Refresh",

        // Per-table toolbar
        ["Toolbar_Unsaved"] = "● Unsaved changes",
        ["Btn_Filter"] = "Filter",
        ["Btn_Sort"] = "Sort",
        ["Btn_RowIdentity"] = "Row identity…",
        ["Tip_RowIdentity"] = "No primary key — choose which columns identify a row for edits/deletes",
        ["Btn_View"] = "View  ▾",
        ["Tip_View"] = "View the selected cell's content as Text, Hex, Image or Web",
        ["Btn_SQL"] = "SQL",
        ["Tip_SQL"] = "Show the SQL that Save will run for pending changes",
        ["Btn_Structure"] = "Structure",
        ["Tip_Structure"] = "Show the table structure: Info, DDL and Indexes",
        ["Lbl_RowLimit"] = "Row limit",
        ["Btn_Export"] = "Export",
        ["Tip_Export"] = "Export the current rows to CSV, JSON, XML, HTML or Excel",
        ["Btn_Reload"] = "Reload",
        ["Btn_SaveChanges"] = "Save changes",

        // Filter popup
        ["Filter_Title"] = "Filter",
        ["Filter_MatchAll"] = "Match all (AND)",
        ["Filter_MatchAny"] = "Match any (OR)",
        ["Filter_AddCondition"] = "＋ Add condition",
        // Sort popup
        ["Sort_Title"] = "Sort",
        ["Sort_AddLevel"] = "＋ Add level",
        // View popup
        ["View_Auto"] = "Auto-detect",
        ["View_Text"] = "Text",
        ["View_Hex"] = "Hex",
        ["View_Image"] = "Image",
        ["View_Web"] = "Web",
        ["View_HidePanel"] = "Hide panel",

        // Common buttons
        ["Btn_Clear"] = "Clear",
        ["Btn_Apply"] = "Apply",
        ["Btn_Cancel"] = "Cancel",
        ["Btn_Save"] = "Save",
        ["Btn_Browse"] = "Browse…",

        // Empty state
        ["Empty_NoTable"] = "No table open",
        ["Empty_Hint"] = "Double-click a table in the tree to open it in a new tab.",
        ["Tab_Objects"] = "Objects",
        ["Tip_RowsLoaded"] = "Rows loaded: {0:N0}  (limit {1:N0})",
        ["Tip_DocsLoaded"] = "Documents loaded: {0:N0}  (limit {1:N0})",
        ["Tip_Key"] = "Key: {0}",

        // Object list (Objects tab)
        ["OL_OpenTable"] = "Open",
        ["OL_DesignTable"] = "Design",
        ["OL_RenameTable"] = "Rename…",
        ["OL_NewTable"] = "New Table",
        ["OL_DeleteTable"] = "Drop…",
        ["OL_Tables"] = "tables",
        ["OL_Views"] = "views",
        ["OL_Functions"] = "functions",
        ["OL_Procedures"] = "procedures",
        ["OL_Collections"] = "collections",
        ["Bar_Connection"] = "Connection",
        ["Bar_NewQuery"] = "New Query",
        ["Bar_Table"] = "Table",
        ["Bar_View"] = "View",
        ["Bar_Function"] = "Function",
        ["Bar_Procedure"] = "Stored Proc",
        ["Bar_Refresh"] = "Refresh",
        ["Bar_VisualDesigner"] = "Visual Designer",
        ["Bar_Users"] = "Users",
        ["Bar_ManageUsers"] = "Manage Users & Roles…",
        ["Bar_NewUser"] = "New User…",
        ["Bar_NewRole"] = "New Role…",
        ["Col_Name"] = "Name",
        ["Col_Schema"] = "Schema",
        ["Col_Rows"] = "Rows",
        ["Col_Modified"] = "Modified Date",
        ["Col_Comment"] = "Comment",
        ["OL_Count"] = "{0} object(s)",

        // Drop confirmation
        ["Btn_Yes"] = "Yes",
        ["Btn_Delete"] = "Delete",
        ["ObjType_table"] = "table",
        ["ObjType_view"] = "view",
        ["ObjType_function"] = "function",
        ["ObjType_procedure"] = "procedure",
        ["Rename_TitleFmt"] = "Rename {0}",
        ["Rename_Q"] = "New name for {0} “{1}”:",
        ["Rename_InvalidName"] = "Name must not be empty.",
        ["Drop_TitleFmt"] = "Drop {0}",
        ["Drop_Q"] = "Permanently drop {0} “{1}”?",
        ["Drop_DataLoss"] = "⚠ ALL the data in this table will be permanently lost.",
        ["Drop_Refs"] = "⚠ These objects reference it:",
        ["Drop_AndMore"] = "…and {0} more",
        ["Drop_CannotUndo"] = "This action CANNOT be undone — there is no way to backtrack once it's dropped.",

        // Settings dialog
        ["Settings_Title"] = "Settings",
        ["Settings_WhenOpening"] = "When opening a table",
        ["Settings_DefaultRowLimit"] = "Default row limit",
        ["Settings_OpenStructure"] = "Open the Structure panel by default",
        ["Settings_DefaultSection"] = "Default section",
        ["Settings_OpenSql"] = "Open the SQL preview panel by default",
        ["Settings_OpenDetail"] = "Open the Cell detail panel by default",
        ["Settings_ConvertClarion"] = "Convert Clarion date / time / timestamp columns by default",
        ["Settings_ApplyNote"] = "Changes apply to tables opened from now on.",
        ["Settings_Language"] = "Language",
        ["Settings_Theme"] = "Theme",
        ["Settings_Interface"] = "Interface",

        // Context menu
        ["Ctx_Open"] = "Open",
        ["Ctx_Design"] = "Design",
        ["Ctx_Rename"] = "Rename…",
        ["Ctx_CopyTable"] = "Copy",
        ["Ctx_PasteTable"] = "Paste",
        ["Ctx_GenerateInsert"] = "Generate INSERT script…",
        ["Ctx_ImportData"] = "Import data…",
        ["Ctx_Drop"] = "Drop…",
        ["Ctx_Edit"] = "Edit",
        ["Ctx_Execute"] = "Execute…",
        ["Ctx_Refresh"] = "Refresh",
        ["Ctx_NewTable"] = "New Table…",
        ["Ctx_NewView"] = "New View…",
        ["Ctx_NewFunction"] = "New Function…",
        ["Ctx_NewProcedure"] = "New Procedure…",

        // Import dialog
        ["Import_Title"] = "Import data",
        ["Import_ChooseFile"] = "Choose a CSV or Excel (.xlsx) file…",
        ["Import_FirstRowHeader"] = "First row contains column names",
        ["Import_MapColumns"] = "Map source columns to table columns",
        ["Import_Skip"] = "(skip)",
        ["Import_Importing"] = "Importing…",
        ["Import_Button"] = "Import",

        // Structure inspector
        ["Insp_Structure"] = "Structure",
        ["Insp_Info"] = "Info",
        ["Insp_Ddl"] = "DDL",
        ["Insp_Indexes"] = "Indexes",
        ["Insp_NoIndexes"] = "No indexes.",
        ["Tip_Pin"] = "Pin / pop out to a floating window",
        ["Hdr_Table"] = "Table",
        ["Hdr_View"] = "View",
        ["Info_Connection"] = "Connection:",
        ["Info_Database"] = "Database:",
        ["Info_Schema"] = "Schema:",
        ["Info_Oid"] = "OID:",
        ["Info_Owner"] = "Owner:",
        ["Info_Collation"] = "Collation:",
        ["Info_DataSize"] = "Data size:",
        ["Info_IndexSize"] = "Index size:",
        ["Info_TotalSize"] = "Total size:",
        ["Info_Comment"] = "Comment:",
        ["Info_Table"] = "Table:",
        ["Info_Columns"] = "Columns:",
        ["Info_PrimaryKey"] = "Primary key:",
        ["Info_Indexes"] = "Indexes:",
        ["Info_Rows"] = "Rows:",
        ["Info_Created"] = "Created:",
        ["Info_Modified"] = "Modified:",
        ["Info_None"] = "(none)",
        ["Rel_None"] = "No foreign-key relationships.",
        ["Rel_References"] = "This table references →",
        ["Rel_ReferencedBy"] = "← Referenced by",
        ["Clarion_Fields"] = "Clarion fields",

        // SQL preview pane
        ["Sql_PreviewTitle"] = "SQL preview",
        ["Sql_PreviewSubtitle"] = "— statements that Save will run for pending changes",
        ["Sql_NoPending"] = "-- No pending changes.",
        ["Sql_PreviewOnly"] = "Preview only — values are sent as parameters at save time.",
        ["Sql_ExecuteNow"] = "Execute now",

        // Cell detail pane
        ["Detail_Cell"] = "Cell:",
        ["Detail_NoneSelected"] = "(none selected)",
        ["Detail_NotImage"] = "Not a recognized image — try Hex.",
        ["Detail_ApplyToCell"] = "Apply to cell",

        // MongoDB
        ["Info_Collection"] = "Collection:",
        ["Info_Documents"] = "Documents:",
        ["Info_SampledFields"] = "Fields:",
        ["Info_Fields"] = "Fields (sampled):",
        ["Mongo_NoRelationships"] = "MongoDB collections have no foreign-key relationships.",
        ["Mongo_NoIndexes"] = "Index details aren't shown for MongoDB collections.",
        ["Mongo_ReadOnly"] = "Read-only view — MongoDB editing isn't supported yet.",
    };

    public static readonly Dictionary<string, string> Es = new(StringComparer.Ordinal)
    {
        // Menú — Archivo
        ["Menu_File"] = "_Archivo",
        ["Menu_NewConnection"] = "Nueva conexión",
        ["Menu_NewQuery"] = "Nueva consulta",
        ["Menu_QueryBuilder"] = "Generador de consultas",
        ["Menu_ExportTable"] = "Exportar tabla actual…",
        ["Menu_Settings"] = "Configuración…",
        ["Menu_Exit"] = "Salir",
        // Menú — Conexión
        ["Menu_Connection"] = "_Conexión",
        ["Menu_AddConnection"] = "Agregar conexión",
        ["Menu_EditConnection"] = "Editar conexión",
        ["Menu_RemoveConnection"] = "Quitar conexión",
        ["Menu_Refresh"] = "Actualizar",
        // Menú — Ver
        ["Menu_View"] = "_Ver",
        ["Menu_StructurePanel"] = "Panel de estructura",
        ["Menu_SqlPanel"] = "Panel de vista previa SQL",
        ["Menu_CellDetailPanel"] = "Panel de detalle de celda",
        // Menú — Ayuda
        ["Menu_Help"] = "A_yuda",
        ["Menu_Documentation"] = "Guía del usuario",
        ["Help_Title"] = "DataPortStudio — Guía del usuario",
        ["Menu_GitHub"] = "Repositorio de GitHub",
        ["Menu_LatestRelease"] = "Última versión",
        ["Menu_About"] = "Acerca de DataPortStudio",

        // Barra lateral
        ["Sidebar_Connections"] = "CONEXIONES",
        ["Filter_TablesPlaceholder"] = "Filtrar tablas…",
        ["Filter_TablesTooltip"] = "Escriba para filtrar tablas (y esquemas/bases de datos) por nombre",
        ["Btn_Add"] = "Agregar",
        ["Btn_Edit"] = "Editar",
        ["Btn_Remove"] = "Quitar",
        ["Btn_Refresh"] = "Actualizar",

        // Barra de herramientas de la tabla
        ["Toolbar_Unsaved"] = "● Cambios sin guardar",
        ["Btn_Filter"] = "Filtrar",
        ["Btn_Sort"] = "Ordenar",
        ["Btn_RowIdentity"] = "Identidad de fila…",
        ["Tip_RowIdentity"] = "Sin clave principal — elija qué columnas identifican una fila para editar/eliminar",
        ["Btn_View"] = "Ver  ▾",
        ["Tip_View"] = "Ver el contenido de la celda seleccionada como Texto, Hex, Imagen o Web",
        ["Btn_SQL"] = "SQL",
        ["Tip_SQL"] = "Mostrar el SQL que ejecutará Guardar para los cambios pendientes",
        ["Btn_Structure"] = "Estructura",
        ["Tip_Structure"] = "Mostrar la estructura de la tabla: Info, DDL e Índices",
        ["Lbl_RowLimit"] = "Límite de filas",
        ["Btn_Export"] = "Exportar",
        ["Tip_Export"] = "Exportar las filas actuales a CSV, JSON, XML, HTML o Excel",
        ["Btn_Reload"] = "Recargar",
        ["Btn_SaveChanges"] = "Guardar cambios",

        // Ventana de filtro
        ["Filter_Title"] = "Filtro",
        ["Filter_MatchAll"] = "Coincidir todo (Y)",
        ["Filter_MatchAny"] = "Coincidir cualquiera (O)",
        ["Filter_AddCondition"] = "＋ Agregar condición",
        // Ventana de orden
        ["Sort_Title"] = "Ordenar",
        ["Sort_AddLevel"] = "＋ Agregar nivel",
        // Ventana de vista
        ["View_Auto"] = "Detección automática",
        ["View_Text"] = "Texto",
        ["View_Hex"] = "Hex",
        ["View_Image"] = "Imagen",
        ["View_Web"] = "Web",
        ["View_HidePanel"] = "Ocultar panel",

        // Botones comunes
        ["Btn_Clear"] = "Limpiar",
        ["Btn_Apply"] = "Aplicar",
        ["Btn_Cancel"] = "Cancelar",
        ["Btn_Save"] = "Guardar",
        ["Btn_Browse"] = "Examinar…",

        // Estado vacío
        ["Empty_NoTable"] = "Ninguna tabla abierta",
        ["Empty_Hint"] = "Haga doble clic en una tabla del árbol para abrirla en una nueva pestaña.",
        ["Tab_Objects"] = "Objetos",
        ["Tip_RowsLoaded"] = "Filas cargadas: {0:N0}  (límite {1:N0})",
        ["Tip_DocsLoaded"] = "Documentos cargados: {0:N0}  (límite {1:N0})",
        ["Tip_Key"] = "Clave: {0}",

        // Lista de objetos
        ["OL_OpenTable"] = "Abrir",
        ["OL_DesignTable"] = "Diseñar",
        ["OL_RenameTable"] = "Renombrar…",
        ["OL_NewTable"] = "Nueva tabla",
        ["OL_DeleteTable"] = "Eliminar…",
        ["OL_Tables"] = "tablas",
        ["OL_Views"] = "vistas",
        ["OL_Functions"] = "funciones",
        ["OL_Procedures"] = "procedimientos",
        ["OL_Collections"] = "colecciones",
        ["Bar_Connection"] = "Conexión",
        ["Bar_NewQuery"] = "Nueva consulta",
        ["Bar_Table"] = "Tabla",
        ["Bar_View"] = "Vista",
        ["Bar_Function"] = "Función",
        ["Bar_Procedure"] = "Proc. Almac.",
        ["Bar_Refresh"] = "Actualizar",
        ["Bar_VisualDesigner"] = "Diseñador visual",
        ["Bar_Users"] = "Usuarios",
        ["Bar_ManageUsers"] = "Administrar usuarios y roles…",
        ["Bar_NewUser"] = "Nuevo usuario…",
        ["Bar_NewRole"] = "Nuevo rol…",
        ["Col_Name"] = "Nombre",
        ["Col_Schema"] = "Esquema",
        ["Col_Rows"] = "Filas",
        ["Col_Modified"] = "Fecha de modificación",
        ["Col_Comment"] = "Comentario",
        ["OL_Count"] = "{0} objeto(s)",

        // Confirmación de eliminación
        ["Btn_Yes"] = "Sí",
        ["Btn_Delete"] = "Eliminar",
        ["ObjType_table"] = "la tabla",
        ["ObjType_view"] = "la vista",
        ["ObjType_function"] = "la función",
        ["ObjType_procedure"] = "el procedimiento",
        ["Rename_TitleFmt"] = "Renombrar {0}",
        ["Rename_Q"] = "Nuevo nombre para {0} “{1}”:",
        ["Rename_InvalidName"] = "El nombre no puede estar vacío.",
        ["Drop_TitleFmt"] = "Eliminar {0}",
        ["Drop_Q"] = "¿Eliminar permanentemente {0} “{1}”?",
        ["Drop_DataLoss"] = "⚠ TODOS los datos de esta tabla se perderán permanentemente.",
        ["Drop_Refs"] = "⚠ Estos objetos la referencian:",
        ["Drop_AndMore"] = "…y {0} más",
        ["Drop_CannotUndo"] = "Esta acción NO se puede deshacer — no hay forma de revertir una vez eliminado.",

        // Configuración
        ["Settings_Title"] = "Configuración",
        ["Settings_WhenOpening"] = "Al abrir una tabla",
        ["Settings_DefaultRowLimit"] = "Límite de filas predeterminado",
        ["Settings_OpenStructure"] = "Abrir el panel de estructura de forma predeterminada",
        ["Settings_DefaultSection"] = "Sección predeterminada",
        ["Settings_OpenSql"] = "Abrir el panel de vista previa SQL de forma predeterminada",
        ["Settings_OpenDetail"] = "Abrir el panel de detalle de celda de forma predeterminada",
        ["Settings_ConvertClarion"] = "Convertir columnas de fecha/hora/marca de tiempo Clarion de forma predeterminada",
        ["Settings_ApplyNote"] = "Los cambios se aplican a las tablas abiertas a partir de ahora.",
        ["Settings_Language"] = "Idioma",
        ["Settings_Theme"] = "Tema",
        ["Settings_Interface"] = "Interfaz",

        // Menú contextual
        ["Ctx_Open"] = "Abrir",
        ["Ctx_Design"] = "Diseñar",
        ["Ctx_Rename"] = "Renombrar…",
        ["Ctx_CopyTable"] = "Copiar",
        ["Ctx_PasteTable"] = "Pegar",
        ["Ctx_GenerateInsert"] = "Generar script INSERT…",
        ["Ctx_ImportData"] = "Importar datos…",
        ["Ctx_Drop"] = "Eliminar…",
        ["Ctx_Edit"] = "Editar",
        ["Ctx_Execute"] = "Ejecutar…",
        ["Ctx_Refresh"] = "Actualizar",
        ["Ctx_NewTable"] = "Nueva tabla…",
        ["Ctx_NewView"] = "Nueva vista…",
        ["Ctx_NewFunction"] = "Nueva función…",
        ["Ctx_NewProcedure"] = "Nuevo procedimiento…",

        // Importar
        ["Import_Title"] = "Importar datos",
        ["Import_ChooseFile"] = "Elija un archivo CSV o Excel (.xlsx)…",
        ["Import_FirstRowHeader"] = "La primera fila contiene los nombres de columna",
        ["Import_MapColumns"] = "Asignar columnas de origen a columnas de la tabla",
        ["Import_Skip"] = "(omitir)",
        ["Import_Importing"] = "Importando…",
        ["Import_Button"] = "Importar",

        // Inspector de estructura
        ["Insp_Structure"] = "Estructura",
        ["Insp_Info"] = "Información",
        ["Insp_Ddl"] = "DDL",
        ["Insp_Indexes"] = "Índices",
        ["Insp_NoIndexes"] = "Sin índices.",
        ["Tip_Pin"] = "Fijar / desacoplar en una ventana flotante",
        ["Hdr_Table"] = "Tabla",
        ["Hdr_View"] = "Vista",
        ["Info_Connection"] = "Conexión:",
        ["Info_Database"] = "Base de datos:",
        ["Info_Schema"] = "Esquema:",
        ["Info_Oid"] = "OID:",
        ["Info_Owner"] = "Propietario:",
        ["Info_Collation"] = "Intercalación:",
        ["Info_DataSize"] = "Tamaño de datos:",
        ["Info_IndexSize"] = "Tamaño de índices:",
        ["Info_TotalSize"] = "Tamaño total:",
        ["Info_Comment"] = "Comentario:",
        ["Info_Table"] = "Tabla:",
        ["Info_Columns"] = "Columnas:",
        ["Info_PrimaryKey"] = "Clave principal:",
        ["Info_Indexes"] = "Índices:",
        ["Info_Rows"] = "Filas:",
        ["Info_Created"] = "Creada:",
        ["Info_Modified"] = "Modificada:",
        ["Info_None"] = "(ninguna)",
        ["Rel_None"] = "Sin relaciones de clave externa.",
        ["Rel_References"] = "Esta tabla referencia →",
        ["Rel_ReferencedBy"] = "← Referenciada por",
        ["Clarion_Fields"] = "Campos Clarion",

        // Panel de vista previa SQL
        ["Sql_PreviewTitle"] = "Vista previa SQL",
        ["Sql_PreviewSubtitle"] = "— sentencias que Guardar ejecutará para los cambios pendientes",
        ["Sql_NoPending"] = "-- Sin cambios pendientes.",
        ["Sql_PreviewOnly"] = "Solo vista previa: los valores se envían como parámetros al guardar.",
        ["Sql_ExecuteNow"] = "Ejecutar ahora",

        // Panel de detalle de celda
        ["Detail_Cell"] = "Celda:",
        ["Detail_NoneSelected"] = "(ninguna seleccionada)",
        ["Detail_NotImage"] = "No es una imagen reconocida — pruebe Hex.",
        ["Detail_ApplyToCell"] = "Aplicar a la celda",

        // MongoDB
        ["Info_Collection"] = "Colección:",
        ["Info_Documents"] = "Documentos:",
        ["Info_SampledFields"] = "Campos:",
        ["Info_Fields"] = "Campos (muestra):",
        ["Mongo_NoRelationships"] = "Las colecciones de MongoDB no tienen relaciones de clave externa.",
        ["Mongo_NoIndexes"] = "Los detalles de índices no se muestran para colecciones de MongoDB.",
        ["Mongo_ReadOnly"] = "Vista de solo lectura — la edición de MongoDB aún no es compatible.",
    };
}
