namespace DataPortStudio.Services;

/// <summary>Translation tables. English is the fallback; Spanish is the first added language.</summary>
public static class Strings
{
    public static string Get(string key, string lang)
    {
        if (lang == "es" && Es.TryGetValue(key, out var es)) return es;
        return En.TryGetValue(key, out var en) ? en : key;
    }

    public static readonly Dictionary<string, string> En = new(StringComparer.Ordinal)
    {
        // Menu — File
        ["Menu_File"] = "_File",
        ["Menu_NewConnection"] = "New Connection",
        ["Menu_NewQuery"] = "New Query",
        ["Menu_QueryBuilder"] = "Query Builder",
        ["Menu_ExportTable"] = "Export current table…",
        ["Menu_Settings"] = "Settings…",
        ["Menu_Exit"] = "Exit",
        // Menu — Connection
        ["Menu_Connection"] = "_Connection",
        ["Menu_AddConnection"] = "Add Connection",
        ["Menu_EditConnection"] = "Edit Connection",
        ["Menu_RemoveConnection"] = "Remove Connection",
        ["Menu_Refresh"] = "Refresh",
        // Menu — View
        ["Menu_View"] = "_View",
        ["Menu_StructurePanel"] = "Structure panel",
        ["Menu_SqlPanel"] = "SQL preview panel",
        ["Menu_CellDetailPanel"] = "Cell detail panel",
        // Menu — Help
        ["Menu_Help"] = "_Help",
        ["Menu_Documentation"] = "User Guide",
        ["Help_Title"] = "DataPortStudio — User Guide",
        ["Menu_GitHub"] = "GitHub Repository",
        ["Menu_LatestRelease"] = "Latest Release",
        ["Menu_About"] = "About DataPortStudio",

        // Sidebar
        ["Sidebar_Connections"] = "CONNECTIONS",
        ["Filter_TablesPlaceholder"] = "Filter tables…",
        ["Filter_TablesTooltip"] = "Type to filter tables (and schemas/databases) by name",
        ["Btn_Add"] = "Add",
        ["Btn_Edit"] = "Edit",
        ["Btn_Remove"] = "Remove",
        ["Btn_Refresh"] = "Refresh",

        // Per-table toolbar
        ["Toolbar_Unsaved"] = "● Unsaved changes",
        ["Btn_Filter"] = "Filter",
        ["Btn_Sort"] = "Sort",
        ["Btn_RowIdentity"] = "Row identity…",
        ["Tip_RowIdentity"] = "No primary key — choose which columns identify a row for edits/deletes",
        ["Btn_View"] = "View  ▾",
        ["Tip_View"] = "View the selected cell's content as Text, Hex, Image or Web",
        ["Btn_SQL"] = "SQL",
        ["Tip_SQL"] = "Show the SQL that Save will run for pending changes",
        ["Btn_Structure"] = "Structure",
        ["Tip_Structure"] = "Show the table structure: Info, DDL and Indexes",
        ["Lbl_RowLimit"] = "Row limit",
        ["Btn_Export"] = "Export",
        ["Tip_Export"] = "Export the current rows to CSV, JSON, XML, HTML or Excel",
        ["Btn_Reload"] = "Reload",
        ["Btn_SaveChanges"] = "Save changes",

        // Filter popup
        ["Filter_Title"] = "Filter",
        ["Filter_MatchAll"] = "Match all (AND)",
        ["Filter_MatchAny"] = "Match any (OR)",
        ["Filter_AddCondition"] = "＋ Add condition",
        // Sort popup
        ["Sort_Title"] = "Sort",
        ["Sort_AddLevel"] = "＋ Add level",
        // View popup
        ["View_Auto"] = "Auto-detect",
        ["View_Text"] = "Text",
        ["View_Hex"] = "Hex",
        ["View_Image"] = "Image",
        ["View_Web"] = "Web",
        ["View_HidePanel"] = "Hide panel",

        // Common buttons
        ["Btn_Clear"] = "Clear",
        ["Btn_Apply"] = "Apply",
        ["Btn_Cancel"] = "Cancel",
        ["Btn_Accept"] = "Accept",
        ["Btn_Save"] = "Save",
        ["Btn_Browse"] = "Browse…",

        // Empty state
        ["Empty_NoTable"] = "No table open",
        ["Empty_Hint"] = "Double-click a table in the tree to open it in a new tab.",
        ["Tab_Objects"] = "Objects",
        ["Tip_RowsLoaded"] = "Rows loaded: {0:N0}  (limit {1:N0})",
        ["Tip_DocsLoaded"] = "Documents loaded: {0:N0}  (limit {1:N0})",
        ["Tip_Key"] = "Key: {0}",

        // Object list (Objects tab)
        ["OL_OpenTable"] = "Open",
        ["OL_DesignTable"] = "Design",
        ["OL_RenameTable"] = "Rename…",
        ["OL_NewTable"] = "New Table",
        ["OL_DeleteTable"] = "Drop…",
        ["OL_Tables"] = "tables",
        ["OL_Views"] = "views",
        ["OL_Functions"] = "functions",
        ["OL_Procedures"] = "procedures",
        ["OL_Collections"] = "collections",
        ["Bar_Connection"] = "Connection",
        ["Bar_NewQuery"] = "New Query",
        ["Bar_Table"] = "Table",
        ["Bar_View"] = "View",
        ["Bar_Function"] = "Function",
        ["Bar_Procedure"] = "Stored Proc",
        ["Bar_Refresh"] = "Refresh",
        ["Bar_VisualDesigner"] = "Visual Designer",
        ["Bar_Users"] = "Users",
        ["Bar_ManageUsers"] = "Manage Users & Roles…",
        ["Bar_NewUser"] = "New User…",
        ["Bar_NewRole"] = "New Role…",
        ["Col_Name"] = "Name",
        ["Col_Schema"] = "Schema",
        ["Col_Rows"] = "Rows",
        ["Col_Modified"] = "Modified Date",
        ["Col_Comment"] = "Comment",
        ["OL_Count"] = "{0} object(s)",
        ["OL_ReadingFiles"] = "reading files… ({0}/{1})",
        ["OL_LocatorPlaceholder"] = "Locate by name…",
        ["OL_LocatorTooltip"] = "Move to objects whose name contains this text without hiding the other rows.",
        ["OL_FilterPlaceholder"] = "Filter by name…",
        ["OL_FilterTooltip"] = "Show only objects whose name contains this text.",
        ["OL_LocatorNoMatches"] = "No matches",
        ["OL_LocatorPosition"] = "{0}/{1}",

        // Drop confirmation
        ["Btn_Yes"] = "Yes",
        ["Btn_Delete"] = "Delete",
        ["ObjType_table"] = "table",
        ["ObjType_view"] = "view",
        ["ObjType_function"] = "function",
        ["ObjType_procedure"] = "procedure",
        ["Rename_TitleFmt"] = "Rename {0}",
        ["Rename_Q"] = "New name for {0} “{1}”:",
        ["Rename_InvalidName"] = "Name must not be empty.",
        ["Drop_TitleFmt"] = "Drop {0}",
        ["Drop_Q"] = "Permanently drop {0} “{1}”?",
        ["Drop_DataLoss"] = "⚠ ALL the data in this table will be permanently lost.",
        ["Drop_Refs"] = "⚠ These objects reference it:",
        ["Drop_AndMore"] = "…and {0} more",
        ["Drop_CannotUndo"] = "This action CANNOT be undone — there is no way to backtrack once it's dropped.",
        ["DbRename_Title"] = "Rename database",
        ["DbRename_Message"] = "Warning: renaming database “{0}” can break saved queries. Active connections will be closed and uncommitted transactions will be rolled back.\n\nEnter the new name:",
        ["DbRename_Unsupported"] = "This database engine does not support safe, atomic database renaming.",
        ["DbRename_Success"] = "Renamed database '{0}' to '{1}'.",
        ["DbRename_Failed"] = "Database rename failed",
        ["DbDelete_Title"] = "Delete database",
        ["DbDelete_Warning"] = "WARNING: Database “{0}” and all its data will be permanently deleted. Active connections will be closed and uncommitted transactions will be rolled back. This action cannot be undone.",
        ["DbDelete_Confirmation"] = "Type the database name “{0}” exactly to confirm:",
        ["DbDelete_Success"] = "Deleted database '{0}'.",
        ["DbDelete_Failed"] = "Database deletion failed",
        ["DbCreate_Title"] = "Create database",
        ["DbCreate_Engine"] = "Create a new database on {0}.",
        ["DbCreate_Name"] = "Database name",
        ["DbCreate_SqlServerCollation"] = "Collation (optional)",
        ["DbCreate_SqlServerHint"] = "Leave blank to use the server default.",
        ["DbCreate_SqlServerRecovery"] = "Recovery model",
        ["DbCreate_SqlServerCompatibility"] = "Compatibility level",
        ["DbCreate_SqlServerFiles"] = "Database files",
        ["DbCreate_SqlServerDataFile"] = "Data file",
        ["DbCreate_SqlServerLogFile"] = "Transaction log file",
        ["DbCreate_LogicalName"] = "Logical name",
        ["DbCreate_PhysicalPath"] = "Physical path on the server",
        ["DbCreate_InitialSizeMb"] = "Initial size (MB)",
        ["DbCreate_MaxSizeMb"] = "Maximum (MB)",
        ["DbCreate_GrowthMb"] = "Growth (MB)",
        ["DbCreate_MaxSizeHint"] = "Leave Maximum blank for unlimited. Paths refer to the SQL Server machine, not this computer.",
        ["DbCreate_LoadingDefaults"] = "Loading defaults from SQL Server…",
        ["DbCreate_DefaultsLoaded"] = "Defaults loaded from the model database and server file locations.",
        ["DbCreate_DefaultsFailed"] = "Could not load server defaults: {0}. You can still enter the values manually.",
        ["DbCreate_BothPathsRequired"] = "Enter both the data and log paths, or leave both blank to use SQL Server defaults.",
        ["DbCreate_PositiveNumber"] = "enter a number greater than zero.",
        ["DbCreate_PostgresOwner"] = "Owner (optional — current user by default)",
        ["DbCreate_PostgresEncoding"] = "Encoding",
        ["DbCreate_MySqlCharset"] = "Character set",
        ["DbCreate_MySqlCollation"] = "Collation (optional)",
        ["DbCreate_MongoCollection"] = "Initial collection",
        ["DbCreate_MongoHint"] = "MongoDB only persists a new database after its first collection is created.",
        ["DbCreate_Create"] = "Create",
        ["DbCreate_NameRequired"] = "Enter a database name.",
        ["DbCreate_CollectionRequired"] = "Enter an initial collection name.",
        ["DbCreate_Unsupported"] = "This connection type does not contain multiple server-level databases.",
        ["DbCreate_Success"] = "Created database '{0}'.",
        ["DbCreate_Failed"] = "Database creation failed",
        ["DbBackup_Title"] = "Back up database",
        ["DbBackup_Progress"] = "Backing up database '{0}'…",
        ["DbBackup_Success"] = "Backed up database '{0}'.",
        ["DbBackup_SuccessPath"] = "Database '{0}' was backed up to:\n{1}",
        ["DbBackup_Failed"] = "Database backup failed",
        ["DbBackup_ToolMissing"] = "The required native utility ({0}) was not found. Install the database client tools and make sure the utility is available in PATH.",
        ["DbRestore_Title"] = "Restore database",
        ["DbRestore_Warning"] = "WARNING: Restoring database “{0}” from the following file will replace its current contents and close active connections. This action cannot be undone.\n\n{1}",
        ["DbRestore_Confirmation"] = "Type the database name “{0}” exactly to confirm:",
        ["DbRestore_Restore"] = "Restore",
        ["DbRestore_Progress"] = "Restoring database '{0}'…",
        ["DbRestore_Success"] = "Restored database '{0}'.",
        ["DbRestore_Failed"] = "Database restore failed",
        ["DbRestore_InvalidBackup"] = "The selected file does not contain a valid SQL Server backup set.",
        ["DbRestore_WrongDatabase"] = "The backup belongs to database '{0}', not '{1}'. Select a backup created from the target database.",
        ["DbScript_Title"] = "Database script — {0}",
        ["DbScript_Progress"] = "Generating complete script for database '{0}'…",
        ["DbScript_Success"] = "Generated complete script for database '{0}'.",
        ["DbScript_Failed"] = "Database script generation failed",

        // Settings dialog
        ["Settings_Title"] = "Settings",
        ["Settings_WhenOpening"] = "When opening a table",
        ["Settings_DefaultRowLimit"] = "Default row limit",
        ["Settings_OpenStructure"] = "Open the Structure panel by default",
        ["Settings_DefaultSection"] = "Default section",
        ["Settings_OpenSql"] = "Open the SQL preview panel by default",
        ["Settings_OpenDetail"] = "Open the Cell detail panel by default",
        ["Settings_ConvertClarion"] = "Convert Clarion date / time / timestamp columns by default",
        ["Settings_ApplyNote"] = "Search changes immediately; query location and table defaults apply to newly opened items.",
        ["Settings_Language"] = "Language",
        ["Settings_Theme"] = "Theme",
        ["Settings_Interface"] = "Interface",
        ["Settings_ObjectSearchMode"] = "Objects search",
        ["Settings_SearchLocator"] = "Locator — keep all rows",
        ["Settings_SearchFilter"] = "Filter — show matches only",
        ["Settings_QueryOpenMode"] = "New query opens in",
        ["Settings_QueryWindow"] = "Separate window",
        ["Settings_QueryDocked"] = "Docked tab",
        ["Bar_ThemeLight"] = "Light",
        ["Bar_ThemeDark"] = "Dark",
        ["Tip_ThemeLight"] = "Switch to light theme",
        ["Tip_ThemeDark"] = "Switch to dark theme",

        // Context menu
        ["Ctx_Open"] = "Open",
        ["Ctx_Design"] = "Design",
        ["Ctx_Rename"] = "Rename…",
        ["Ctx_RenameDatabase"] = "Rename database…",
        ["Ctx_CreateDatabase"] = "Create database…",
        ["Ctx_BackupDatabase"] = "Back up…",
        ["Ctx_RestoreDatabase"] = "Restore…",
        ["Ctx_GenerateDatabaseScript"] = "Generate database script…",
        ["Ctx_CopyTable"] = "Copy",
        ["Ctx_PasteTable"] = "Paste",
        ["Ctx_GenerateInsert"] = "Generate INSERT script…",
        ["Ctx_GenerateScript"] = "Generate object script…",
        ["Ctx_ImportData"] = "Import data…",
        ["Ctx_Drop"] = "Drop…",
        ["Ctx_DeleteDatabase"] = "Delete database…",
        ["Ctx_Edit"] = "Edit",
        ["Ctx_Execute"] = "Execute…",
        ["Ctx_Refresh"] = "Refresh",
        ["Ctx_NewTable"] = "New Table…",
        ["Ctx_NewView"] = "New View…",
        ["Ctx_NewFunction"] = "New Function…",
        ["Ctx_NewProcedure"] = "New Procedure…",
        ["Script_Title"] = "Object script — {0}",
        ["Script_Generating"] = "Generating script for '{0}'…",
        ["Script_Generated"] = "Generated script for '{0}'.",
        ["Script_Failed"] = "Script generation failed",
        ["Script_DefinitionUnavailable"] = "The object definition is not available or the object is encrypted.",

        // Import dialog
        ["Import_Title"] = "Import data",
        ["Import_ChooseFile"] = "Choose a CSV or Excel (.xlsx) file…",
        ["Import_FirstRowHeader"] = "First row contains column names",
        ["Import_MapColumns"] = "Map source columns to table columns",
        ["Import_Skip"] = "(skip)",
        ["Import_Importing"] = "Importing…",
        ["Import_Button"] = "Import",

        // Structure inspector
        ["Insp_Structure"] = "Structure",
        ["Insp_Info"] = "Info",
        ["Insp_Ddl"] = "DDL",
        ["Insp_Indexes"] = "Indexes",
        ["Insp_NoIndexes"] = "No indexes.",
        ["Tip_Pin"] = "Pin / pop out to a floating window",
        ["Hdr_Table"] = "Table",
        ["Hdr_View"] = "View",
        ["Info_Connection"] = "Connection:",
        ["Info_Database"] = "Database:",
        ["Info_Schema"] = "Schema:",
        ["Info_Oid"] = "OID:",
        ["Info_Owner"] = "Owner:",
        ["Info_Collation"] = "Collation:",
        ["Info_DataSize"] = "Data size:",
        ["Info_IndexSize"] = "Index size:",
        ["Info_TotalSize"] = "Total size:",
        ["Info_Comment"] = "Comment:",
        ["Info_Table"] = "Table:",
        ["Info_Columns"] = "Columns:",
        ["Info_PrimaryKey"] = "Primary key:",
        ["Info_Indexes"] = "Indexes:",
        ["Info_Rows"] = "Rows:",
        ["Info_Created"] = "Created:",
        ["Info_Modified"] = "Modified:",
        ["Info_None"] = "(none)",
        ["Rel_None"] = "No foreign-key relationships.",
        ["Rel_References"] = "This table references →",
        ["Rel_ReferencedBy"] = "← Referenced by",
        ["Clarion_Fields"] = "Clarion fields",

        // SQL preview pane
        ["Sql_PreviewTitle"] = "SQL preview",
        ["Sql_PreviewSubtitle"] = "— statements that Save will run for pending changes",
        ["Sql_NoPending"] = "-- No pending changes.",
        ["Sql_PreviewOnly"] = "Preview only — values are sent as parameters at save time.",
        ["Sql_ExecuteNow"] = "Execute now",

        // Cell detail pane
        ["Detail_Cell"] = "Cell:",
        ["Detail_NoneSelected"] = "(none selected)",
        ["Detail_NotImage"] = "Not a recognized image — try Hex.",
        ["Detail_ApplyToCell"] = "Apply to cell",

        // MongoDB
        ["Info_Collection"] = "Collection:",
        ["Info_Documents"] = "Documents:",
        ["Info_SampledFields"] = "Fields:",
        ["Info_Fields"] = "Fields (sampled):",
        ["Mongo_NoRelationships"] = "MongoDB collections have no foreign-key relationships.",
        ["Mongo_NoIndexes"] = "Index details aren't shown for MongoDB collections.",
        ["Mongo_ReadOnly"] = "Read-only view — MongoDB editing isn't supported yet.",
    };

    public static readonly Dictionary<string, string> Es = new(StringComparer.Ordinal)
    {
        // Menú — Archivo
        ["Menu_File"] = "_Archivo",
        ["Menu_NewConnection"] = "Nueva conexión",
        ["Menu_NewQuery"] = "Nueva consulta",
        ["Menu_QueryBuilder"] = "Generador de consultas",
        ["Menu_ExportTable"] = "Exportar tabla actual…",
        ["Menu_Settings"] = "Configuración…",
        ["Menu_Exit"] = "Salir",
        // Menú — Conexión
        ["Menu_Connection"] = "_Conexión",
        ["Menu_AddConnection"] = "Agregar conexión",
        ["Menu_EditConnection"] = "Editar conexión",
        ["Menu_RemoveConnection"] = "Quitar conexión",
        ["Menu_Refresh"] = "Actualizar",
        // Menú — Ver
        ["Menu_View"] = "_Ver",
        ["Menu_StructurePanel"] = "Panel de estructura",
        ["Menu_SqlPanel"] = "Panel de vista previa SQL",
        ["Menu_CellDetailPanel"] = "Panel de detalle de celda",
        // Menú — Ayuda
        ["Menu_Help"] = "A_yuda",
        ["Menu_Documentation"] = "Guía del usuario",
        ["Help_Title"] = "DataPortStudio — Guía del usuario",
        ["Menu_GitHub"] = "Repositorio de GitHub",
        ["Menu_LatestRelease"] = "Última versión",
        ["Menu_About"] = "Acerca de DataPortStudio",

        // Barra lateral
        ["Sidebar_Connections"] = "CONEXIONES",
        ["Filter_TablesPlaceholder"] = "Filtrar tablas…",
        ["Filter_TablesTooltip"] = "Escriba para filtrar tablas (y esquemas/bases de datos) por nombre",
        ["Btn_Add"] = "Agregar",
        ["Btn_Edit"] = "Editar",
        ["Btn_Remove"] = "Quitar",
        ["Btn_Refresh"] = "Actualizar",

        // Barra de herramientas de la tabla
        ["Toolbar_Unsaved"] = "● Cambios sin guardar",
        ["Btn_Filter"] = "Filtrar",
        ["Btn_Sort"] = "Ordenar",
        ["Btn_RowIdentity"] = "Identidad de fila…",
        ["Tip_RowIdentity"] = "Sin clave principal — elija qué columnas identifican una fila para editar/eliminar",
        ["Btn_View"] = "Ver  ▾",
        ["Tip_View"] = "Ver el contenido de la celda seleccionada como Texto, Hex, Imagen o Web",
        ["Btn_SQL"] = "SQL",
        ["Tip_SQL"] = "Mostrar el SQL que ejecutará Guardar para los cambios pendientes",
        ["Btn_Structure"] = "Estructura",
        ["Tip_Structure"] = "Mostrar la estructura de la tabla: Info, DDL e Índices",
        ["Lbl_RowLimit"] = "Límite de filas",
        ["Btn_Export"] = "Exportar",
        ["Tip_Export"] = "Exportar las filas actuales a CSV, JSON, XML, HTML o Excel",
        ["Btn_Reload"] = "Recargar",
        ["Btn_SaveChanges"] = "Guardar cambios",

        // Ventana de filtro
        ["Filter_Title"] = "Filtro",
        ["Filter_MatchAll"] = "Coincidir todo (Y)",
        ["Filter_MatchAny"] = "Coincidir cualquiera (O)",
        ["Filter_AddCondition"] = "＋ Agregar condición",
        // Ventana de orden
        ["Sort_Title"] = "Ordenar",
        ["Sort_AddLevel"] = "＋ Agregar nivel",
        // Ventana de vista
        ["View_Auto"] = "Detección automática",
        ["View_Text"] = "Texto",
        ["View_Hex"] = "Hex",
        ["View_Image"] = "Imagen",
        ["View_Web"] = "Web",
        ["View_HidePanel"] = "Ocultar panel",

        // Botones comunes
        ["Btn_Clear"] = "Limpiar",
        ["Btn_Apply"] = "Aplicar",
        ["Btn_Cancel"] = "Cancelar",
        ["Btn_Accept"] = "Aceptar",
        ["Btn_Save"] = "Guardar",
        ["Btn_Browse"] = "Examinar…",

        // Estado vacío
        ["Empty_NoTable"] = "Ninguna tabla abierta",
        ["Empty_Hint"] = "Haga doble clic en una tabla del árbol para abrirla en una nueva pestaña.",
        ["Tab_Objects"] = "Objetos",
        ["Tip_RowsLoaded"] = "Filas cargadas: {0:N0}  (límite {1:N0})",
        ["Tip_DocsLoaded"] = "Documentos cargados: {0:N0}  (límite {1:N0})",
        ["Tip_Key"] = "Clave: {0}",

        // Lista de objetos
        ["OL_OpenTable"] = "Abrir",
        ["OL_DesignTable"] = "Diseñar",
        ["OL_RenameTable"] = "Renombrar…",
        ["OL_NewTable"] = "Nueva tabla",
        ["OL_DeleteTable"] = "Eliminar…",
        ["OL_Tables"] = "tablas",
        ["OL_Views"] = "vistas",
        ["OL_Functions"] = "funciones",
        ["OL_Procedures"] = "procedimientos",
        ["OL_Collections"] = "colecciones",
        ["Bar_Connection"] = "Conexión",
        ["Bar_NewQuery"] = "Nueva consulta",
        ["Bar_Table"] = "Tabla",
        ["Bar_View"] = "Vista",
        ["Bar_Function"] = "Función",
        ["Bar_Procedure"] = "Proc. Almac.",
        ["Bar_Refresh"] = "Actualizar",
        ["Bar_VisualDesigner"] = "Diseñador visual",
        ["Bar_Users"] = "Usuarios",
        ["Bar_ManageUsers"] = "Administrar usuarios y roles…",
        ["Bar_NewUser"] = "Nuevo usuario…",
        ["Bar_NewRole"] = "Nuevo rol…",
        ["Col_Name"] = "Nombre",
        ["Col_Schema"] = "Esquema",
        ["Col_Rows"] = "Filas",
        ["Col_Modified"] = "Fecha de modificación",
        ["Col_Comment"] = "Comentario",
        ["OL_Count"] = "{0} objeto(s)",
        ["OL_ReadingFiles"] = "leyendo archivos… ({0}/{1})",
        ["OL_LocatorPlaceholder"] = "Localizar por nombre…",
        ["OL_LocatorTooltip"] = "Va a objetos cuyo nombre contiene el texto sin ocultar las demás filas.",
        ["OL_FilterPlaceholder"] = "Filtrar por nombre…",
        ["OL_FilterTooltip"] = "Muestra únicamente objetos cuyo nombre contiene este texto.",
        ["OL_LocatorNoMatches"] = "Sin coincidencias",
        ["OL_LocatorPosition"] = "{0}/{1}",

        // Confirmación de eliminación
        ["Btn_Yes"] = "Sí",
        ["Btn_Delete"] = "Eliminar",
        ["ObjType_table"] = "la tabla",
        ["ObjType_view"] = "la vista",
        ["ObjType_function"] = "la función",
        ["ObjType_procedure"] = "el procedimiento",
        ["Rename_TitleFmt"] = "Renombrar {0}",
        ["Rename_Q"] = "Nuevo nombre para {0} “{1}”:",
        ["Rename_InvalidName"] = "El nombre no puede estar vacío.",
        ["Drop_TitleFmt"] = "Eliminar {0}",
        ["Drop_Q"] = "¿Eliminar permanentemente {0} “{1}”?",
        ["Drop_DataLoss"] = "⚠ TODOS los datos de esta tabla se perderán permanentemente.",
        ["Drop_Refs"] = "⚠ Estos objetos la referencian:",
        ["Drop_AndMore"] = "…y {0} más",
        ["Drop_CannotUndo"] = "Esta acción NO se puede deshacer — no hay forma de revertir una vez eliminado.",
        ["DbRename_Title"] = "Renombrar base de datos",
        ["DbRename_Message"] = "Advertencia: renombrar la base de datos “{0}” puede afectar consultas guardadas. Las conexiones activas se cerrarán y las transacciones sin confirmar se revertirán.\n\nIntroduzca el nuevo nombre:",
        ["DbRename_Unsupported"] = "Este motor no permite renombrar bases de datos de forma segura y atómica.",
        ["DbRename_Success"] = "Se renombró la base de datos '{0}' a '{1}'.",
        ["DbRename_Failed"] = "No se pudo renombrar la base de datos",
        ["DbDelete_Title"] = "Eliminar base de datos",
        ["DbDelete_Warning"] = "ADVERTENCIA: la base de datos “{0}” y todos sus datos se eliminarán permanentemente. Las conexiones activas se cerrarán y las transacciones sin confirmar se revertirán. Esta acción no se puede deshacer.",
        ["DbDelete_Confirmation"] = "Escriba exactamente el nombre de la base de datos “{0}” para confirmar:",
        ["DbDelete_Success"] = "Se eliminó la base de datos '{0}'.",
        ["DbDelete_Failed"] = "No se pudo eliminar la base de datos",
        ["DbCreate_Title"] = "Crear base de datos",
        ["DbCreate_Engine"] = "Crear una nueva base de datos en {0}.",
        ["DbCreate_Name"] = "Nombre de la base de datos",
        ["DbCreate_SqlServerCollation"] = "Intercalación (opcional)",
        ["DbCreate_SqlServerHint"] = "Déjelo vacío para usar la configuración predeterminada del servidor.",
        ["DbCreate_SqlServerRecovery"] = "Modelo de recuperación",
        ["DbCreate_SqlServerCompatibility"] = "Nivel de compatibilidad",
        ["DbCreate_SqlServerFiles"] = "Archivos de la base de datos",
        ["DbCreate_SqlServerDataFile"] = "Archivo de datos",
        ["DbCreate_SqlServerLogFile"] = "Archivo del registro de transacciones",
        ["DbCreate_LogicalName"] = "Nombre lógico",
        ["DbCreate_PhysicalPath"] = "Ruta física en el servidor",
        ["DbCreate_InitialSizeMb"] = "Tamaño inicial (MB)",
        ["DbCreate_MaxSizeMb"] = "Máximo (MB)",
        ["DbCreate_GrowthMb"] = "Crecimiento (MB)",
        ["DbCreate_MaxSizeHint"] = "Deje Máximo vacío para permitir crecimiento ilimitado. Las rutas pertenecen al equipo de SQL Server, no a este equipo.",
        ["DbCreate_LoadingDefaults"] = "Cargando valores predeterminados desde SQL Server…",
        ["DbCreate_DefaultsLoaded"] = "Valores cargados desde la base model y las ubicaciones de archivos del servidor.",
        ["DbCreate_DefaultsFailed"] = "No se pudieron cargar los valores del servidor: {0}. Puede introducirlos manualmente.",
        ["DbCreate_BothPathsRequired"] = "Introduzca las rutas de datos y registro, o deje ambas vacías para usar las predeterminadas de SQL Server.",
        ["DbCreate_PositiveNumber"] = "introduzca un número mayor que cero.",
        ["DbCreate_PostgresOwner"] = "Propietario (opcional — usuario actual de forma predeterminada)",
        ["DbCreate_PostgresEncoding"] = "Codificación",
        ["DbCreate_MySqlCharset"] = "Juego de caracteres",
        ["DbCreate_MySqlCollation"] = "Intercalación (opcional)",
        ["DbCreate_MongoCollection"] = "Colección inicial",
        ["DbCreate_MongoHint"] = "MongoDB solo conserva una base nueva después de crear su primera colección.",
        ["DbCreate_Create"] = "Crear",
        ["DbCreate_NameRequired"] = "Introduzca un nombre para la base de datos.",
        ["DbCreate_CollectionRequired"] = "Introduzca el nombre de la colección inicial.",
        ["DbCreate_Unsupported"] = "Este tipo de conexión no contiene varias bases de datos a nivel de servidor.",
        ["DbCreate_Success"] = "Se creó la base de datos '{0}'.",
        ["DbCreate_Failed"] = "No se pudo crear la base de datos",
        ["DbBackup_Title"] = "Respaldar base de datos",
        ["DbBackup_Progress"] = "Respaldando la base de datos '{0}'…",
        ["DbBackup_Success"] = "Se respaldó la base de datos '{0}'.",
        ["DbBackup_SuccessPath"] = "La base de datos '{0}' se respaldó en:\n{1}",
        ["DbBackup_Failed"] = "No se pudo respaldar la base de datos",
        ["DbBackup_ToolMissing"] = "No se encontró la utilidad nativa requerida ({0}). Instale las herramientas cliente del motor y asegúrese de que la utilidad esté disponible en PATH.",
        ["DbRestore_Title"] = "Restaurar base de datos",
        ["DbRestore_Warning"] = "ADVERTENCIA: Restaurar la base de datos “{0}” desde el siguiente archivo reemplazará su contenido actual y cerrará las conexiones activas. Esta acción no se puede deshacer.\n\n{1}",
        ["DbRestore_Confirmation"] = "Escriba exactamente el nombre de la base de datos “{0}” para confirmar:",
        ["DbRestore_Restore"] = "Restaurar",
        ["DbRestore_Progress"] = "Restaurando la base de datos '{0}'…",
        ["DbRestore_Success"] = "Se restauró la base de datos '{0}'.",
        ["DbRestore_Failed"] = "No se pudo restaurar la base de datos",
        ["DbRestore_InvalidBackup"] = "El archivo seleccionado no contiene un conjunto de respaldo válido de SQL Server.",
        ["DbRestore_WrongDatabase"] = "El respaldo pertenece a la base de datos '{0}', no a '{1}'. Seleccione un respaldo creado desde la base de datos de destino.",
        ["DbScript_Title"] = "Script de la base de datos — {0}",
        ["DbScript_Progress"] = "Generando el script completo de la base de datos '{0}'…",
        ["DbScript_Success"] = "Se generó el script completo de la base de datos '{0}'.",
        ["DbScript_Failed"] = "No se pudo generar el script de la base de datos",

        // Configuración
        ["Settings_Title"] = "Configuración",
        ["Settings_WhenOpening"] = "Al abrir una tabla",
        ["Settings_DefaultRowLimit"] = "Límite de filas predeterminado",
        ["Settings_OpenStructure"] = "Abrir el panel de estructura de forma predeterminada",
        ["Settings_DefaultSection"] = "Sección predeterminada",
        ["Settings_OpenSql"] = "Abrir el panel de vista previa SQL de forma predeterminada",
        ["Settings_OpenDetail"] = "Abrir el panel de detalle de celda de forma predeterminada",
        ["Settings_ConvertClarion"] = "Convertir columnas de fecha/hora/marca de tiempo Clarion de forma predeterminada",
        ["Settings_ApplyNote"] = "La búsqueda cambia de inmediato; la ubicación de consultas y las opciones de tabla se aplican a elementos nuevos.",
        ["Settings_Language"] = "Idioma",
        ["Settings_Theme"] = "Tema",
        ["Settings_Interface"] = "Interfaz",
        ["Settings_ObjectSearchMode"] = "Búsqueda de objetos",
        ["Settings_SearchLocator"] = "Locator — mantener todas las filas",
        ["Settings_SearchFilter"] = "Filtro — mostrar coincidencias",
        ["Settings_QueryOpenMode"] = "Abrir nueva consulta en",
        ["Settings_QueryWindow"] = "Ventana separada",
        ["Settings_QueryDocked"] = "Pestaña acoplada",
        ["Bar_ThemeLight"] = "Claro",
        ["Bar_ThemeDark"] = "Oscuro",
        ["Tip_ThemeLight"] = "Cambiar al tema claro",
        ["Tip_ThemeDark"] = "Cambiar al tema oscuro",

        // Menú contextual
        ["Ctx_Open"] = "Abrir",
        ["Ctx_Design"] = "Diseñar",
        ["Ctx_Rename"] = "Renombrar…",
        ["Ctx_RenameDatabase"] = "Renombrar base de datos…",
        ["Ctx_CreateDatabase"] = "Crear base de datos…",
        ["Ctx_BackupDatabase"] = "Respaldar…",
        ["Ctx_RestoreDatabase"] = "Restaurar…",
        ["Ctx_GenerateDatabaseScript"] = "Generar script de la base de datos…",
        ["Ctx_CopyTable"] = "Copiar",
        ["Ctx_PasteTable"] = "Pegar",
        ["Ctx_GenerateInsert"] = "Generar script INSERT…",
        ["Ctx_GenerateScript"] = "Generar script del objeto…",
        ["Ctx_ImportData"] = "Importar datos…",
        ["Ctx_Drop"] = "Eliminar…",
        ["Ctx_DeleteDatabase"] = "Eliminar base de datos…",
        ["Ctx_Edit"] = "Editar",
        ["Ctx_Execute"] = "Ejecutar…",
        ["Ctx_Refresh"] = "Actualizar",
        ["Ctx_NewTable"] = "Nueva tabla…",
        ["Ctx_NewView"] = "Nueva vista…",
        ["Ctx_NewFunction"] = "Nueva función…",
        ["Ctx_NewProcedure"] = "Nuevo procedimiento…",
        ["Script_Title"] = "Script del objeto — {0}",
        ["Script_Generating"] = "Generando script para '{0}'…",
        ["Script_Generated"] = "Se generó el script para '{0}'.",
        ["Script_Failed"] = "No se pudo generar el script",
        ["Script_DefinitionUnavailable"] = "La definición del objeto no está disponible o el objeto está cifrado.",

        // Importar
        ["Import_Title"] = "Importar datos",
        ["Import_ChooseFile"] = "Elija un archivo CSV o Excel (.xlsx)…",
        ["Import_FirstRowHeader"] = "La primera fila contiene los nombres de columna",
        ["Import_MapColumns"] = "Asignar columnas de origen a columnas de la tabla",
        ["Import_Skip"] = "(omitir)",
        ["Import_Importing"] = "Importando…",
        ["Import_Button"] = "Importar",

        // Inspector de estructura
        ["Insp_Structure"] = "Estructura",
        ["Insp_Info"] = "Información",
        ["Insp_Ddl"] = "DDL",
        ["Insp_Indexes"] = "Índices",
        ["Insp_NoIndexes"] = "Sin índices.",
        ["Tip_Pin"] = "Fijar / desacoplar en una ventana flotante",
        ["Hdr_Table"] = "Tabla",
        ["Hdr_View"] = "Vista",
        ["Info_Connection"] = "Conexión:",
        ["Info_Database"] = "Base de datos:",
        ["Info_Schema"] = "Esquema:",
        ["Info_Oid"] = "OID:",
        ["Info_Owner"] = "Propietario:",
        ["Info_Collation"] = "Intercalación:",
        ["Info_DataSize"] = "Tamaño de datos:",
        ["Info_IndexSize"] = "Tamaño de índices:",
        ["Info_TotalSize"] = "Tamaño total:",
        ["Info_Comment"] = "Comentario:",
        ["Info_Table"] = "Tabla:",
        ["Info_Columns"] = "Columnas:",
        ["Info_PrimaryKey"] = "Clave principal:",
        ["Info_Indexes"] = "Índices:",
        ["Info_Rows"] = "Filas:",
        ["Info_Created"] = "Creada:",
        ["Info_Modified"] = "Modificada:",
        ["Info_None"] = "(ninguna)",
        ["Rel_None"] = "Sin relaciones de clave externa.",
        ["Rel_References"] = "Esta tabla referencia →",
        ["Rel_ReferencedBy"] = "← Referenciada por",
        ["Clarion_Fields"] = "Campos Clarion",

        // Panel de vista previa SQL
        ["Sql_PreviewTitle"] = "Vista previa SQL",
        ["Sql_PreviewSubtitle"] = "— sentencias que Guardar ejecutará para los cambios pendientes",
        ["Sql_NoPending"] = "-- Sin cambios pendientes.",
        ["Sql_PreviewOnly"] = "Solo vista previa: los valores se envían como parámetros al guardar.",
        ["Sql_ExecuteNow"] = "Ejecutar ahora",

        // Panel de detalle de celda
        ["Detail_Cell"] = "Celda:",
        ["Detail_NoneSelected"] = "(ninguna seleccionada)",
        ["Detail_NotImage"] = "No es una imagen reconocida — pruebe Hex.",
        ["Detail_ApplyToCell"] = "Aplicar a la celda",

        // MongoDB
        ["Info_Collection"] = "Colección:",
        ["Info_Documents"] = "Documentos:",
        ["Info_SampledFields"] = "Campos:",
        ["Info_Fields"] = "Campos (muestra):",
        ["Mongo_NoRelationships"] = "Las colecciones de MongoDB no tienen relaciones de clave externa.",
        ["Mongo_NoIndexes"] = "Los detalles de índices no se muestran para colecciones de MongoDB.",
        ["Mongo_ReadOnly"] = "Vista de solo lectura — la edición de MongoDB aún no es compatible.",
    };
}
