using System.Windows;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Input;
using System.Windows.Media;
using DataPortStudio.Services;
using DataPortStudio.ViewModels;

namespace DataPortStudio.Behaviors;

/// <summary>
/// Column freezing for the data grids. Freezing a column moves it to the front of the grid and
/// pins it there, so it stays put while the rest of the table scrolls sideways; its header shows
/// a 📌 while it is frozen. Freezes are remembered per table tab, so a refresh, a sort or a tab
/// switch brings them back.
/// </summary>
public static class DataGridFreeze
{
    // ---- state ------------------------------------------------------------

    /// <summary>Prefixed to a frozen column's header so the pin shows up in front of its name.</summary>
    private const string Pin = "📌  ";

    /// <summary>Where the column sat before it was frozen, so unfreezing can put it back.</summary>
    private static readonly DependencyProperty HomeIndexProperty =
        DependencyProperty.RegisterAttached(
            "HomeIndex", typeof(int), typeof(DataGridFreeze), new PropertyMetadata(-1));

    /// <summary>Frozen column names for grids with no view-model to remember them (query results).</summary>
    private static readonly DependencyProperty LocalFrozenProperty =
        DependencyProperty.RegisterAttached(
            "LocalFrozen", typeof(List<string>), typeof(DataGridFreeze), new PropertyMetadata(null));

    /// <summary>
    /// Standalone use on grids that don't carry <see cref="DataGridClarion"/> (query results):
    /// installs the header right-click menu with the freeze commands.
    /// </summary>
    public static readonly DependencyProperty EnabledProperty =
        DependencyProperty.RegisterAttached(
            "Enabled", typeof(bool), typeof(DataGridFreeze),
            new PropertyMetadata(false, OnEnabledChanged));

    public static bool GetEnabled(DependencyObject o) => (bool)o.GetValue(EnabledProperty);
    public static void SetEnabled(DependencyObject o, bool value) => o.SetValue(EnabledProperty, value);

    private static void OnEnabledChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
    {
        if (d is not DataGrid grid) return;
        if ((bool)e.NewValue)
        {
            grid.PreviewMouseRightButtonUp += OnHeaderRightClick;
            grid.AutoGeneratedColumns += OnAutoGeneratedColumns;
        }
        else
        {
            grid.PreviewMouseRightButtonUp -= OnHeaderRightClick;
            grid.AutoGeneratedColumns -= OnAutoGeneratedColumns;
        }
    }

    private static void OnAutoGeneratedColumns(object? sender, EventArgs e)
    {
        if (sender is DataGrid grid) Restore(grid);
    }

    private static void OnHeaderRightClick(object sender, MouseButtonEventArgs e)
    {
        if (sender is not DataGrid grid) return;

        var header = FindAncestor<DataGridColumnHeader>(e.OriginalSource as DependencyObject);
        if (header?.Column is not { } column) return;
        if (string.IsNullOrEmpty(DataGridClarion.GetColumnName(column))) return;

        var menu = new ContextMenu();
        AddMenuItems(menu, grid, column);
        menu.PlacementTarget = header;
        menu.IsOpen = true;
        e.Handled = true;
    }

    // ---- menu ------------------------------------------------------------

    /// <summary>Adds the freeze / unfreeze commands for <paramref name="column"/> to a header menu.</summary>
    public static void AddMenuItems(ContextMenu menu, DataGrid grid, DataGridColumn column)
    {
        var loc = LocalizationManager.Instance;
        var frozen = IsFrozen(grid, column);

        var toggle = new MenuItem
        {
            Header = frozen ? loc["Grid_UnfreezeColumn"] : loc["Grid_FreezeColumn"] + "  📌"
        };
        toggle.Click += (_, _) =>
        {
            if (frozen) Unfreeze(grid, column);
            else Freeze(grid, column);
        };
        menu.Items.Add(toggle);

        // Only worth offering once more than this one column is pinned.
        if (grid.FrozenColumnCount > 1 || (grid.FrozenColumnCount == 1 && !frozen))
        {
            var all = new MenuItem { Header = loc["Grid_UnfreezeAll"] };
            all.Click += (_, _) => UnfreezeAll(grid);
            menu.Items.Add(all);
        }
    }

    // ---- freeze / unfreeze ----------------------------------------------

    public static bool IsFrozen(DataGrid grid, DataGridColumn column) =>
        grid.FrozenColumnCount > 0 && column.DisplayIndex < grid.FrozenColumnCount;

    /// <summary>Pins the column: it moves to the front of the grid and stops scrolling sideways.</summary>
    public static void Freeze(DataGrid grid, DataGridColumn column)
    {
        var name = DataGridClarion.GetColumnName(column);
        if (string.IsNullOrEmpty(name)) return;

        var store = Store(grid);
        if (!store.Contains(name, StringComparer.OrdinalIgnoreCase))
        {
            if (GetHomeIndex(column) < 0) SetHomeIndex(column, column.DisplayIndex);
            store.Add(name);
        }
        Apply(grid, store);
        ScrollToFront(grid);
    }

    /// <summary>Unpins the column and returns it to the position it had before it was frozen.</summary>
    public static void Unfreeze(DataGrid grid, DataGridColumn column)
    {
        var name = DataGridClarion.GetColumnName(column);
        if (string.IsNullOrEmpty(name)) return;

        var store = Store(grid);
        store.RemoveAll(n => string.Equals(n, name, StringComparison.OrdinalIgnoreCase));
        Apply(grid, store);

        var home = GetHomeIndex(column);
        SetHomeIndex(column, -1);
        if (home >= 0 && grid.Columns.Count > 0)
            TrySetDisplayIndex(column, Math.Clamp(home, grid.FrozenColumnCount, grid.Columns.Count - 1));
    }

    public static void UnfreezeAll(DataGrid grid)
    {
        var store = Store(grid);
        var pinned = grid.Columns
            .Where(c => store.Contains(DataGridClarion.GetColumnName(c), StringComparer.OrdinalIgnoreCase))
            .ToList();
        store.Clear();
        Apply(grid, store);

        foreach (var column in pinned)
        {
            var home = GetHomeIndex(column);
            SetHomeIndex(column, -1);
            if (home >= 0 && grid.Columns.Count > 0)
                TrySetDisplayIndex(column, Math.Clamp(home, 0, grid.Columns.Count - 1));
        }
    }

    /// <summary>Re-applies the remembered freezes after the grid regenerated its columns.</summary>
    public static void Restore(DataGrid grid)
    {
        foreach (var column in grid.Columns) SetHomeIndex(column, -1);
        Apply(grid, Store(grid));
    }

    /// <summary>Lays the frozen columns out as the first N columns and pins them there.</summary>
    private static void Apply(DataGrid grid, List<string> names)
    {
        // Release the pin first so DisplayIndex can be shuffled freely.
        grid.FrozenColumnCount = 0;

        var slot = 0;
        foreach (var name in names)
        {
            var column = Find(grid, name);
            if (column is null) continue;
            if (GetHomeIndex(column) < 0) SetHomeIndex(column, column.DisplayIndex);
            TrySetDisplayIndex(column, slot);
            slot++;
        }

        // Always leave one scrolling column, otherwise the grid has nothing left to scroll.
        grid.FrozenColumnCount = Math.Min(slot, Math.Max(grid.Columns.Count - 1, 0));

        foreach (var column in grid.Columns)
            ShowPin(column, IsFrozen(grid, column));
    }

    /// <summary>Re-adds the 📌 after something else rewrote the column header.</summary>
    public static void RefreshPin(DataGrid grid, DataGridColumn column) =>
        ShowPin(column, IsFrozen(grid, column));

    /// <summary>Adds or removes the pin prefix on a column header.</summary>
    private static void ShowPin(DataGridColumn column, bool frozen)
    {
        if (column.Header is not string text) return;

        var bare = text.StartsWith(Pin, StringComparison.Ordinal) ? text[Pin.Length..] : text;
        var wanted = frozen ? Pin + bare : bare;
        if (!string.Equals(text, wanted, StringComparison.Ordinal)) column.Header = wanted;
    }

    /// <summary>A newly pinned column sits at the left edge — show that edge.</summary>
    private static void ScrollToFront(DataGrid grid)
    {
        var scroller = FindDescendant<ScrollViewer>(grid);
        scroller?.ScrollToHorizontalOffset(0);
    }

    // ---- helpers ---------------------------------------------------------

    /// <summary>
    /// Where a grid's frozen column names live: the table tab remembers them (so they survive a
    /// refresh, a sort or a tab switch); other grids keep their own list.
    /// </summary>
    private static List<string> Store(DataGrid grid)
    {
        if (grid.DataContext is TableTabViewModel tab) return tab.FrozenColumns;

        if (grid.GetValue(LocalFrozenProperty) is not List<string> local)
        {
            local = new List<string>();
            grid.SetValue(LocalFrozenProperty, local);
        }
        return local;
    }

    private static DataGridColumn? Find(DataGrid grid, string name) =>
        grid.Columns.FirstOrDefault(c =>
            string.Equals(DataGridClarion.GetColumnName(c), name, StringComparison.OrdinalIgnoreCase));

    private static void TrySetDisplayIndex(DataGridColumn column, int index)
    {
        if (index < 0 || column.DisplayIndex == index) return;
        try { column.DisplayIndex = index; } catch { /* column list changed underneath us */ }
    }

    private static int GetHomeIndex(DependencyObject o) => (int)o.GetValue(HomeIndexProperty);
    private static void SetHomeIndex(DependencyObject o, int value) => o.SetValue(HomeIndexProperty, value);

    private static T? FindAncestor<T>(DependencyObject? current) where T : DependencyObject
    {
        while (current is not null and not T)
            current = VisualTreeHelper.GetParent(current);
        return current as T;
    }

    private static T? FindDescendant<T>(DependencyObject root) where T : DependencyObject
    {
        for (var i = 0; i < VisualTreeHelper.GetChildrenCount(root); i++)
        {
            var child = VisualTreeHelper.GetChild(root, i);
            if (child is T hit) return hit;
            if (FindDescendant<T>(child) is { } deeper) return deeper;
        }
        return null;
    }
}
