using System.ComponentModel;
using System.Windows.Controls;
using System.Windows.Threading;
using DataPortStudio.ViewModels;

namespace DataPortStudio.Behaviors;

/// <summary>
/// Keeps the sort arrow in each column header in step with the sort actually in effect — whether
/// it came from clicking the header or from the toolbar's Sort panel, which sorts the query
/// rather than the grid. The header template draws the ▲ / ▼ from
/// <see cref="DataGridColumn.SortDirection"/>; this is what keeps that property honest.
/// </summary>
public static class DataGridSortIndicator
{
    /// <summary>Starts tracking a grid's sort state.</summary>
    public static void Attach(DataGrid grid)
    {
        grid.Sorting += OnSorting;
        grid.AutoGeneratedColumns += OnAutoGeneratedColumns;
    }

    public static void Detach(DataGrid grid)
    {
        grid.Sorting -= OnSorting;
        grid.AutoGeneratedColumns -= OnAutoGeneratedColumns;
    }

    // The grid applies the sort after this event, so read the result on the next dispatcher pass.
    private static void OnSorting(object? sender, DataGridSortingEventArgs e)
    {
        if (sender is DataGrid grid) SyncLater(grid);
    }

    private static void OnAutoGeneratedColumns(object? sender, EventArgs e)
    {
        if (sender is DataGrid grid) SyncLater(grid);
    }

    private static void SyncLater(DataGrid grid) =>
        grid.Dispatcher.BeginInvoke(new Action(() => Sync(grid)), DispatcherPriority.Background);

    /// <summary>Marks every column header with the direction the grid is sorted by, if any.</summary>
    public static void Sync(DataGrid grid)
    {
        var order = ActiveSort(grid);

        foreach (var column in grid.Columns)
        {
            var name = DataGridClarion.GetColumnName(column);
            var level = order.FindIndex(o =>
                string.Equals(o.Column, name, StringComparison.OrdinalIgnoreCase));

            column.SortDirection = level < 0 ? null : order[level].Direction;
        }
    }

    /// <summary>
    /// The columns the grid is sorted by, in order. A header click lands in the collection view's
    /// sort descriptions; the toolbar's Sort panel sorts the query itself, so its levels are read
    /// from the view-model instead.
    /// </summary>
    private static List<(string Column, ListSortDirection Direction)> ActiveSort(DataGrid grid)
    {
        var order = new List<(string, ListSortDirection)>();

        try
        {
            foreach (var sort in grid.Items.SortDescriptions)
                if (!string.IsNullOrEmpty(sort.PropertyName))
                    order.Add((sort.PropertyName, sort.Direction));
        }
        catch { /* this view doesn't expose sort descriptions */ }
        if (order.Count > 0) return order;

        if (grid.DataContext is TableTabViewModel tab)
        {
            foreach (var level in tab.SortLevels)
                if (!string.IsNullOrWhiteSpace(level.Column))
                    order.Add((level.Column!, level.Direction == SortDirection.Desc
                        ? ListSortDirection.Descending
                        : ListSortDirection.Ascending));
        }

        return order;
    }
}
